name: Pytest
  
on:
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:
        python-version: ["3.12.7"]
    env:
      DISPLAY: ':99.0'
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  

      - uses: tlambert03/setup-qt-libs@v1
      - name: Ubuntu setup for pytest-qt
        run: |  
          sudo apt-get install -y xvfb libnss3 libxdamage1 libasound2
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX

      - name: Build .deb package with virtual environment
        run: |
    
          pip install pyinstaller
          
          # Создание необходимых директорий для .deb пакета
          mkdir -p ~/calcul/DEBIAN
          mkdir -p ~/calcul/usr/local/bin
          mkdir -p ~/calcul/usr/local/lib/python3.*/site-packages  # Папка для библиотек
      
          # Создание виртуального окружения
          python3 -m venv ~/calcul/venv
          
          # Активация виртуального окружения
          source ~/calcul/venv/bin/activate
      
          # Установка зависимостей в виртуальное окружение из requirements.txt
          pip install --upgrade pip
          pip install -r requirements.txt
      
          # Сборка исполняемого файла с помощью pyinstaller
          pyinstaller --onefile --windowed main.py
          cp dist/main ~/calcul/usr/local/bin/
      
          # Генерация файла control с зависимостями, которые устанавливаются через apt
          echo "Package: calcul
          Version: 1.0
          Architecture: amd64
          Maintainer: Your Name <your.email@example.com>
          Installed-Size: 1024
          Depends: python3, python3-pyqt6
          Section: utils
          Priority: optional
          Description: A PyQt6 calculator application" > ~/calcul/DEBIAN/control
          
          # Добавляем postinst скрипт для активации виртуального окружения
          echo "#!/bin/bash
          # Активируем виртуальное окружение
          source /usr/local/lib/python3.*/dist-packages/calcul/venv/bin/activate
          # Устанавливаем зависимости в виртуальном окружении, если нужно
          pip install --no-cache-dir -r /usr/local/lib/python3.*/dist-packages/calcul/requirements.txt" > ~/calcul/DEBIAN/postinst
          
          # Делаем postinst исполняемым
          chmod +x ~/calcul/DEBIAN/postinst
      
          # Копируем файл requirements.txt в пакет
          cp requirements.txt ~/calcul/usr/local/lib/python3.*/dist-packages/calcul/requirements.txt
      
          # Создание deb-пакета
          dpkg-deb --build ~/calcul
